* Config for a rocky system (server)

** Grab a few essential git repositories


Note, this needs to be reworked (include from file)
#+begin_src python
  #!/usr/bin/python3
  import os
  from pathlib import Path

  home = os.environ["HOME"]
  home_path = Path(home)
  local_sources = f"{home}/.local/src"
  lsrc_path = Path(local_sources)

  repositories = {
      # name: {url, version}
      "dotfiles": "https://github.com/adammccartney/dotfiles.git",
      "stow":  "https://github.com/aspiers/stow.git",
      "neovim": "https://github.com/neovim/neovim.git",
  }

  for k,v in repositories.items():
      if (k == "dotfiles"):
          os.system(f"git clone {v} {home_path}/{k}")
      os.system(f"git clone {v} {lsrc_path}/{k}")
#+end_src

** Bootstrapping tools

#+begin_src conf :tangle ~/dotfiles/.config/rocky/manifests/bootstrap-tools
  clang
  clang-devel
  clang-tools-extra
  cmake
  golang-bin
#+end_src

*** Raku dependencies

Fedora only!

#+begin_src shell
  yum groupinstall 'Development Tools'
  yum install perl-ExtUtils-Command
#+end_src

*** Stow for 

*** cargo

#+begin_src shell
  
#+end_src



* Literate config for a debian system

Here we're going to track packages that we need to bootstrap a system.
Assumes that the base install of the system we are using is Debian/Bullseye

** Dependencies for building emacs from source

As mentioned in [[id:c54194f7-200c-4290-8767-94e361c37e68][emacs 28.1 compilation]], debian requires a whole pile of specific x11
dependencies for building from source


#+begin_src emacs-lisp :tangle ~/dotfiles/.config/debian/manifests/emacs28.1
  build-essential
  libc6-dev
  libjpeg62-turbo
  libncurses5-dev
  libpng-dev
  libtiff5-dev
  libgif-dev
  xaw3dg-dev
  zlib1g-dev
  libx11-dev
  libcairo2-dev
  libgtk-3-dev
  libfreetype6-dev
  libxft-dev
#+end_src

On top of this, both emacs and mu require the meson build tool

#+begin_src shell :tangle ~/dotfiles/.config/python3/manifests/buildtools-requirements.txt
meson==0.62.0
#+end_src

* Pulling individual packages from other pacakge repository



#+begin_src emacs-lisp :tangle etc/apt/sources.list.d/stable-proposed-updates.list
 deb http://deb.debian.org/debian bullseye-proposed-updates main 
#+end_src

#+begin_src emacs-lisp :tangle etc/apt/sources.list.d/testing.list
  deb http://deb.debian.org/debian/ testing main contrib non-free
  deb-src http://deb.debian.org/debian/ testing main contrib non-free
#+end_src

** Apt Pinning in Debian

Warning: recipe for disaster, mind those kittens.

The following is from the man(5) apt preferences
#+begin_src emacs-lisp :tangle etc/apt/preferences.d/preferences
  Explanation: Uninstall or do not install any Debian-originated
  Explanation: package versions other than those in the stable distro
  Package: *
  Pin: release a=stable
  Pin-Priority: 900

  Package: *
  Pin: release a=proposed-updates
  Pin-Priority: 100

  Package: *
  Pin: release o=Debian
  Pin-Priority: -10
#+end_src


To install a package from testing:

The following packages will then not be upgraded until this command is given again
#+begin_src shell
  apt install -t testing vagrant-libvirt
#+end_src


List of packages installed from testing 
#+begin_src conf :tangle ~/dotfiles/.config/debian/manifests/testing.txt
  vagrant-libvirt
  libvirt-daemon-system
  virt-manager
  gcc-multilib
  torbrowser-launc
  tor
  clang
  clangd
#+end_src
         

** Vagrant dependencies

Debian 11 requires pulling the vagrant / libvert packages from testing.
Also it requires a more recent version of a ruby gem

#+begin_src conf :tangle ~/dotfiles/.config/debian/manifests/ruby.txt
          net-ssh --version 7.0.0.beta1
#+end_src
