#!/bin/bash

VERSION=1.24.4
OS=linux
ARCH=amd64

GO_PKG_PREFIX=$HOME/.local/pkg

curl -L -f -o "$GO_PKG_PREFIX"/go"$VERSION"."$OS"-"$ARCH".tar.gz https://go.dev/dl/go1.24.4.linux-amd64.tar.gz
pushd "$GO_PKG_PREFIX"
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.24.4.linux-amd64.tar.gz
popd

