#!/bin/bash


DOTFILES_DIR=${1:-$HOME/dotfiles}
## TODO: make this do stuff
ln -sbv "$DOTFILES_DIR"/vim/.vimrc $HOME/.vimrc
ln -sbv "$DOTFILES_DIR"/vim/.vim $HOME/.vim
ln -sbv "$DOTFILES_DIR"/nvim/.config/nvim $HOME/.config/nvim
ln -sbv "$DOTFILES_DIR"/home-bin/bin $HOME/bin
