#!/bin/sh

# Instead of linking bash config files with stow,
# we're going to append to the files that we need.

DOTFILES_ROOT=$(pwd)
FILES_PATH="$DOTFILES_ROOT/files"
if ! [[ -d "$FILES_PATH" ]]; then
    echo "Error, no files path found"
    exit 1
fi

# backup
# link new
for cfg in aliases functions profile prompt fzf-keybindings git-completion; do
    ln -sbv "$FILES_PATH"/bash-${cfg} "$HOME/.bash_${cfg}"
done
ln -sbv "$FILES_PATH"/bash-rc "$HOME/.bashrc"
