;; This was generated by the graphical installer the first time we configured
;; the system via graphical install using qemu

(use-modules (gnu))
(use-service-modules cups desktop networking ssh xorg)

(operating-system
 (locale "en_GB.utf8")
 (timezone "Europe/Vienna")
 (keyboard-layout (keyboard-layout "de" "nodeadkeys"))
 (host-name "watt")

 ;; List of user accounts
 (users (cons* (user-account
                (name "amccartn")
                (comment "Adam McCartney")
                (group "users")
                (home-directory "/home/amccartn")
                (supplementary-groups '("wheel" "netdev" "audio" "video")))
               %base-user-accounts))

 ;; List of system services
 (services
  (append (list (service gnome-desktop-service-type)

                ;; To configure OpenSSH pass an 'openssh-configuration'
                ;; record as second argument to 'service' below.
                (service openssh-service-type)
                (set-xorg-configuration
                 (xorg-configuration (keyboard-layout keyboard-layout))))

          ;; Default list of services we are appending to
          %desktop-services))

 (bootloader (bootloader-configuration
              (bootloader grub-bootloader)
              (targets (list "/dev/sda"))
              (keyboard-layout keyboard-layout)))
 (swap-devices (list (swap-space
                      (target (uuid
                               "b0e58e3c-f0f1-4a00-9a3e-b0c3b18fc23c")))))

 ;; list of filesystems that get "mounted", their ("UUIDs") can be obtained by running 'bklid' in a terminal.
 (file-systems (cons* (file-system
                       (mount-point "/")
                       (device (uuid
                                "6ba78fae-4a75-4a06-839e-497d3c7b23da"
                                'ext4))
                        (type "ext4")) %base-file-systems)))            

